excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://MauraDudas.github.io
title: MauraDudas
tagline: Sarabande of light and dark
description: Just putting it out there, giving in to the many persuasive people who seem my writing enjoyable. So it should completely be about my thoughts and ideas. All the typos are the fault of my biased half Hungarian autocorrect. It's not amazing. <br />So...yeah. 
paginate: 5